/* Archived personal ULPPL reference (not seeded): 5 days, 35 exercises.
   ex   = id in the exercise library (photos + instructions come from there)
   hu/en = display name override, tip = coaching note in both languages
   mm   = precise muscle map override: [front, back], 1 = primary, 2 = secondary */
window.PLAN = {
  days: [
    { id: 'upper', hu: 'Felsőtest', en: 'Upper', sub: { hu: 'Mell, hát, váll, kar', en: 'Chest, back, shoulders, arms' } },
    { id: 'lower', hu: 'Alsótest', en: 'Lower', sub: { hu: 'Comb, fenék, vádli, has', en: 'Quads, hamstrings, glutes, calves, abs' } },
    { id: 'push', hu: 'Push', en: 'Push', sub: { hu: 'Váll, mell, tricepsz', en: 'Shoulders, chest, triceps' } },
    { id: 'pull', hu: 'Pull', en: 'Pull', sub: { hu: 'Hát, hátsó váll, bicepsz, alkar', en: 'Back, rear delts, biceps, forearms' } },
    { id: 'legs', hu: 'Láb', en: 'Legs', sub: { hu: 'Második lábnap, más szögekből', en: 'Second leg day, different angles' } }
  ],
  items: [
    // ---------- Upper ----------
    { day: 'upper', ex: 'Barbell_Bench_Press_-_Medium_Grip', hu: 'Sík fekvenyomás rúddal', en: 'Barbell bench press', sets: 3, reps: '5–8', rest: 210,
      mm: [{ pec: 1, delt_front: 2 }, { triceps: 2 }],
      tip: { hu: 'A nap nehéz alapgyakorlata, ezért az első. Lapocka hátrahúzva, a rudat a mellbimbó vonalára engedd. Felül ne zárd be teljesen a könyököt.',
             en: 'The heavy compound of the day, so it goes first. Shoulder blades pulled back, lower the bar to nipple line. Don\'t fully lock the elbows at the top.' } },
    { day: 'upper', ex: 'Pullups', hu: 'Húzódzkodás', en: 'Pull-up', sets: 3, reps: '6–10', rest: 150,
      mm: [{ biceps: 2, forearm: 2 }, { lats: 1, traps: 2, delt_rear: 2 }],
      tip: { hu: 'Vállnál kicsit szélesebb felső fogás. Alul nyújtsd ki teljesen a kart, felül az áll menjen a rúd fölé. Ha nem megy 6 ismétlés, használj gumiszalagot vagy segédgépet.',
             en: 'Overhand grip slightly wider than shoulders. Full hang at the bottom, chin over the bar at the top. If you can\'t get 6 reps, use a band or the assisted machine.' } },
    { day: 'upper', ex: 'Incline_Dumbbell_Press', hu: 'Ferde padon nyomás kézisúlyzóval', en: 'Incline dumbbell press', sets: 3, reps: '8–12', rest: 150,
      mm: [{ pec: 1, delt_front: 2 }, { triceps: 2 }],
      tip: { hu: 'A pad 30 fokon. 45 fok fölött már a váll veszi át a munkát. A kézisúlyzó mélyebb nyújtást enged, mint a rúd: alul engedd le a mellkas vonala alá.',
             en: 'Bench at 30°. Above 45° the shoulders take over. Dumbbells allow a deeper stretch than the bar: lower them below chest line.' } },
    { day: 'upper', ex: 'Leverage_Iso_Row', hu: 'Mellel megtámasztott gépi evezés', en: 'Chest-supported machine row', sets: 3, reps: '8–12', rest: 120,
      mm: [{ biceps: 2, forearm: 2 }, { lats: 1, traps: 1, delt_rear: 2 }],
      tip: { hu: 'A mellkas a párnán marad, így a derekad nem tud lendíteni. A könyököd súrolja a törzsed, a végén szorítsd össze a lapockát.',
             en: 'Chest stays on the pad so your lower back can\'t cheat. Elbows brush your torso; squeeze the shoulder blades at the end.' } },
    { day: 'upper', ex: 'Side_Lateral_Raise', hu: 'Oldalra karemelés kézisúlyzóval', en: 'Dumbbell lateral raise', sets: 3, reps: '12–15', rest: 90,
      mm: [{ delt_front: 1 }, { delt_rear: 1, traps: 2 }],
      tip: { hu: 'Váll magasságig emelj, enyhén hajlított könyökkel. Kis súly, lendítés nélkül: ez az izom kis terheléssel is jól nő.',
             en: 'Raise to shoulder height with slightly bent elbows. Light weight, no swinging: this muscle grows well with small loads.' } },
    { day: 'upper', ex: 'Cable_Rope_Overhead_Triceps_Extension', hu: 'Kábeles fej fölötti tricepsz nyújtás', en: 'Cable overhead triceps extension', sets: 3, reps: '10–12', rest: 90,
      mm: [{}, { triceps: 1 }],
      tip: { hu: 'Fordulj el a géptől, lépj egyet előre, a könyököd nézzen kissé kifelé. A fej fölötti helyzet megnyújtja a tricepsz hosszú fejét, ami több növekedést ad, mint a lenyomás.',
             en: 'Face away from the stack, step forward, elbows slightly flared. The overhead position stretches the long head of the triceps, which grows it more than pushdowns.' } },
    { day: 'upper', ex: 'Incline_Dumbbell_Curl', hu: 'Ferdepados bicepszhajlítás', en: 'Incline dumbbell curl', sets: 3, reps: '10–12', rest: 90,
      mm: [{ biceps: 1, forearm: 2 }, {}],
      tip: { hu: 'Hanyatt döntött padon a kar a törzs mögé kerül, így a bicepsz megnyúlt helyzetből indul. Ne lendíts, és alul engedd ki teljesen a kart.',
             en: 'On a reclined bench the arm hangs behind the torso, so the biceps starts stretched. No swinging; fully extend at the bottom.' } },
    // ---------- Lower ----------
    { day: 'lower', ex: 'Barbell_Full_Squat', hu: 'Hátsó guggolás', en: 'Back squat', sets: 3, reps: '5–8', rest: 210,
      mm: [{ quads: 1, adductors: 2, abs: 2 }, { glutes: 1, erectors: 2, hams: 2 }],
      tip: { hu: 'A rúd a lábközép fölött marad. Menj a csípővel a térd vonala alá. A nap első gyakorlata, amíg friss vagy.',
             en: 'Keep the bar over mid-foot. Hips go below knee level. First exercise of the day, while you\'re fresh.' } },
    { day: 'lower', ex: 'Romanian_Deadlift', hu: 'Román felhúzás', en: 'Romanian deadlift', sets: 3, reps: '6–10', rest: 150,
      mm: [{}, { hams: 1, glutes: 1, erectors: 2, lats: 2 }],
      tip: { hu: 'A térd majdnem nyújtva marad, a csípőt told hátra, a rúd a combodon csúszik. Addig menj le, amíg a combhajlító nyúlását érzed.',
             en: 'Knees almost straight, push the hips back, bar slides down the thighs. Go down until you feel the hamstrings stretch.' } },
    { day: 'lower', ex: 'Leg_Press', hu: 'Lábtoló gép', en: 'Leg press', sets: 3, reps: '8–12', rest: 150,
      mm: [{ quads: 1, adductors: 2 }, { glutes: 1, hams: 2 }],
      tip: { hu: 'Vállszéles láb, a talp közepével told. Alul ne emeld el a farkadat a támlától, és ne told ki teljesen a térdet felül.',
             en: 'Feet shoulder-width, push through mid-foot. Don\'t let your hips lift off the pad at the bottom, and don\'t lock the knees at the top.' } },
    { day: 'lower', ex: 'Lying_Leg_Curls', hu: 'Fekvő combhajlító gép', en: 'Lying leg curl', sets: 3, reps: '10–12', rest: 90,
      mm: [{}, { hams: 1, calves: 2 }],
      tip: { hu: 'A párna az Achilles-ín fölött. A csípőd maradjon a padon: ha felemelkedik, túl nagy a súly. A végén szorítsd meg, és lassan engedd vissza.',
             en: 'Pad just above the Achilles. Keep hips on the bench: if they lift, the weight is too heavy. Squeeze at the top, lower slowly.' } },
    { day: 'lower', ex: 'Seated_Calf_Raise', hu: 'Ülő vádliemelés', en: 'Seated calf raise', sets: 4, reps: '10–15', rest: 60,
      mm: [{}, { calves: 1 }],
      tip: { hu: 'Hajlított térdnél a mélyebben fekvő lábközépszár-izom dolgozik. A sarkat engedd mélyre, felül szorítsd meg egy másodpercre. Ne pattogtass.',
             en: 'With bent knees the deeper soleus does the work. Let the heels drop deep, hold a second at the top. No bouncing.' } },
    { day: 'lower', ex: 'Ab_Crunch_Machine', hu: 'Gépi hasprés', en: 'Machine ab crunch', sets: 3, reps: '12–15', rest: 60,
      mm: [{ abs: 1, obliques: 2 }, {}],
      tip: { hu: 'Nem a karral húzod, hanem a hasfalat hajlítod: a mellkas közelít a csípőhöz, a hát kerekedik. Lassan engedd vissza.',
             en: 'Don\'t pull with the arms: flex the abs so the chest moves toward the hips and the back rounds. Return slowly.' } },
    { day: 'lower', ex: 'Thigh_Adductor', hu: 'Combközelítő gép', en: 'Adductor machine', sets: 2, reps: '12–15', rest: 60,
      mm: [{ adductors: 1 }, { glutes: 2 }],
      tip: { hu: 'Opcionális kiegészítés. Engedd szét a térdet nyújtásig, majd húzd össze.',
             en: 'Optional extra. Let the knees open to a stretch, then squeeze together.' } },
    // ---------- Push ----------
    { day: 'push', ex: 'Standing_Military_Press', hu: 'Álló vállból nyomás rúddal', en: 'Standing overhead press', sets: 3, reps: '5–8', rest: 180,
      mm: [{ delt_front: 1, pec: 2, abs: 2 }, { triceps: 1, traps: 2 }],
      tip: { hu: 'A rúd a kulcscsont elől indul. Told a fejed fölé, majd told előre a fejed a rúd alá. Feszes has és fenék, ne hajolj hátra a derékkal.',
             en: 'Bar starts at the collarbone. Press overhead, then push your head through under the bar. Tight abs and glutes, no leaning back.' } },
    { day: 'push', ex: 'Barbell_Incline_Bench_Press_-_Medium_Grip', hu: 'Ferde fekvenyomás rúddal', en: 'Incline barbell bench press', sets: 3, reps: '6–10', rest: 150,
      mm: [{ pec: 1, delt_front: 2 }, { triceps: 2 }],
      tip: { hu: '30 fokos pad. A rudat a kulcscsont alá, a felső mellre engedd, ne a nyakadra.',
             en: '30° bench. Lower the bar to the upper chest just below the collarbone, not to the neck.' } },
    { day: 'push', ex: 'Dips_-_Chest_Version', hu: 'Tolódzkodás', en: 'Dip', sets: 3, reps: '8–12', rest: 150,
      mm: [{ pec: 1, delt_front: 2 }, { triceps: 1 }],
      tip: { hu: 'Ha előredőlsz, a mell dolgozik jobban; egyenes törzzsel a tricepsz. Addig engedd le magad, amíg a felkar párhuzamos a talajjal.',
             en: 'Lean forward for chest, stay upright for triceps. Lower until the upper arm is parallel to the floor.' } },
    { day: 'push', ex: 'Single-Arm_Cable_Crossover', hu: 'Egykezes kábeles tárogatás', en: 'One-arm cable fly', sets: 3, reps: '12–15', rest: 90,
      mm: [{ pec: 1, delt_front: 2 }, {}],
      tip: { hu: 'Felső csigáról lefelé-befelé húzod a kezet a test középvonala elé. A könyök végig ugyanabban a kis szögben marad. Karonként számold.',
             en: 'From a high pulley, pull the hand down and across to the body\'s midline. Elbow angle stays fixed. Count reps per arm.' } },
    { day: 'push', ex: 'Seated_Side_Lateral_Raise', hu: 'Gépi oldalra karemelés', en: 'Machine lateral raise', sets: 3, reps: '12–15', rest: 60, similar: true,
      mm: [{ delt_front: 1 }, { delt_rear: 1, traps: 2 }],
      tip: { hu: 'A gépen a párna a felkaron van, nem a csuklón, így a váll dolgozik, nem a kar. Váll magasságig emelj, és ne húzd fel a vállad a füledhez.',
             en: 'On the machine the pad sits on the upper arm, not the wrist, so the delt does the work. Raise to shoulder height; don\'t shrug.' } },
    { day: 'push', ex: 'Incline_Barbell_Triceps_Extension', hu: 'Koponyatörő ferde padon', en: 'Incline skull crusher', sets: 3, reps: '8–12', rest: 90,
      mm: [{}, { triceps: 1 }],
      tip: { hu: 'Emelt háttámlán hagyd, hogy a karod hátrafelé vándoroljon a fejed mögé: így a tricepsz hosszú feje megnyúlik.',
             en: 'On an inclined bench let the arms drift back behind your head: that stretches the long head of the triceps.' } },
    { day: 'push', ex: 'Cable_One_Arm_Tricep_Extension', hu: 'Egykezes kábeles tricepsz nyújtás', en: 'Single-arm cable triceps extension', sets: 2, reps: '12–15', rest: 60,
      mm: [{}, { triceps: 1 }],
      tip: { hu: 'A könyököd a törzs mellett marad, csak az alkar mozog. Karonként számold.',
             en: 'Elbow stays at your side, only the forearm moves. Count reps per arm.' } },
    // ---------- Pull ----------
    { day: 'pull', ex: 'Bent_Over_Barbell_Row', hu: 'Rúdemelés (hajolt evezés)', en: 'Barbell row', sets: 3, reps: '6–10', rest: 150,
      mm: [{ biceps: 2, forearm: 2 }, { lats: 1, traps: 1, delt_rear: 2, erectors: 2 }],
      tip: { hu: 'Kb. 45 fokos törzsdőlés, egyenes hát. A rudat a köldök felé húzd, a lapockát szorítsd össze. Ha a derekad lendül, csökkentsd a súlyt.',
             en: 'Torso at about 45°, flat back. Pull the bar to the navel and squeeze the shoulder blades. If your lower back swings, drop the weight.' } },
    { day: 'pull', ex: 'Wide-Grip_Lat_Pulldown', hu: 'Lat-húzógép, széles fogás', en: 'Wide-grip lat pulldown', sets: 3, reps: '8–12', rest: 120,
      mm: [{ biceps: 2, forearm: 2 }, { lats: 1, traps: 2, delt_rear: 2 }],
      tip: { hu: 'A rudat a mell elé húzd, ne a tarkód mögé. Vállnál másfélszer szélesebb fogás. A lapockát húzd le először.',
             en: 'Pull the bar to the chest, never behind the neck. Grip about 1.5× shoulder width. Start by pulling the shoulder blades down.' } },
    { day: 'pull', ex: 'Seated_Cable_Rows', hu: 'Ülő kábelhúzás', en: 'Seated cable row', sets: 3, reps: '8–12', rest: 120,
      mm: [{ biceps: 2, forearm: 2 }, { lats: 1, traps: 1, delt_rear: 2 }],
      tip: { hu: 'A könyököd súrolja a törzsed, a lapockát húzd hátra. Ne dőlj előre-hátra a felsőtesttel.',
             en: 'Elbows brush the torso, shoulder blades pull back. Don\'t rock the upper body.' } },
    { day: 'pull', ex: 'Cable_Rear_Delt_Fly', hu: 'Kábeles hátsó vállemelés', en: 'Cable rear delt fly', sets: 3, reps: '12–15', rest: 60,
      mm: [{}, { delt_rear: 1, traps: 2 }],
      tip: { hu: 'Az ellenkező oldali csigát fogd meg, és kifelé-hátra húzd nyújtott könyökkel. Kis súly, sok ismétlés.',
             en: 'Grab the opposite-side pulley and pull out and back with straight elbows. Light weight, high reps.' } },
    { day: 'pull', ex: 'Barbell_Curl', hu: '21-es bicepszhajlítás rúddal', en: '21s barbell curl', sets: 3, reps: '21', rest: 120,
      mm: [{ biceps: 1, forearm: 2 }, {}],
      tip: { hu: 'Egy sorozat három részből áll, pihenő nélkül: 7 ismétlés alulról félmagasságig, 7 félmagasságtól felülre, majd 7 teljes.',
             en: 'One set is three parts with no rest: 7 reps from the bottom to halfway, 7 from halfway to the top, then 7 full reps.' } },
    { day: 'pull', ex: 'Hammer_Curls', hu: 'Kalapácsfogású hajlítás', en: 'Hammer curl', sets: 3, reps: '10–12', rest: 60,
      mm: [{ biceps: 1, forearm: 1 }, {}],
      tip: { hu: 'Semleges fogás: a tenyered egymás felé néz. A bicepsz alatt fekvő karizmot és az alkart terheli.',
             en: 'Neutral grip, palms facing each other. Loads the brachialis under the biceps and the forearm.' } },
    { day: 'pull', ex: 'Seated_Dumbbell_Palms-Up_Wrist_Curl', hu: 'Csuklóhajlítás', en: 'Wrist curl', sets: 2, reps: '15–20', rest: 60,
      mm: [{ forearm: 1 }, {}],
      tip: { hu: 'Ülve, az alkar a combon fekszik, csak a csukló mozog.',
             en: 'Seated, forearms resting on the thighs, only the wrists move.' } },
    // ---------- Legs ----------
    { day: 'legs', ex: 'Front_Barbell_Squat', hu: 'Első guggolás', en: 'Front squat', sets: 3, reps: '6–10', rest: 180,
      mm: [{ quads: 1, abs: 2, adductors: 2 }, { glutes: 2, erectors: 2 }],
      tip: { hu: 'A rúd elöl, a vállon fekszik, a könyök magasan. Egyenesebb a törzs, ezért jobban a comb elejét terheli. Alternatíva: hack-gép.',
             en: 'Bar rests on the front of the shoulders, elbows high. More upright torso, so it hits the quads harder. Alternative: hack squat.' } },
    { day: 'legs', ex: 'Seated_Leg_Curl', hu: 'Ülő combhajlító gép', en: 'Seated leg curl', sets: 3, reps: '10–12', rest: 90,
      mm: [{}, { hams: 1 }],
      tip: { hu: 'Ülve a csípő hajlítva van, ezért a combhajlító megnyúlt helyzetből dolgozik. A térded essen egybe a gép forgástengelyével.',
             en: 'Seated, the hips are flexed so the hamstrings work from a stretched position. Line your knee up with the machine\'s pivot.' } },
    { day: 'legs', ex: 'Barbell_Hip_Thrust', hu: 'Csípőtolás', en: 'Hip thrust', sets: 3, reps: '8–12', rest: 120,
      mm: [{}, { glutes: 1, hams: 2 }],
      tip: { hu: 'A lapocka alsó része a padon, a rúd a csípőd fölött (párnával). Told a csípőt felfelé, amíg a törzs és a comb egy vonalba kerül.',
             en: 'Lower shoulder blades on the bench, bar over the hips (with a pad). Drive the hips up until torso and thighs are in line.' } },
    { day: 'legs', ex: 'Split_Squat_with_Dumbbells', hu: 'Bolgár kitörés', en: 'Bulgarian split squat', sets: 3, reps: '8–10', rest: 120,
      mm: [{ quads: 1, adductors: 2 }, { glutes: 1, hams: 2 }],
      tip: { hu: 'A hátsó láb rüsztje a padon. A súly az első lábon van, a hátsó csak egyensúlyoz. Lábanként számold.',
             en: 'Rear foot on the bench. The weight is on the front leg; the rear one only balances. Count reps per leg.' } },
    { day: 'legs', ex: 'Leg_Extensions', hu: 'Ülő lábnyújtó gép', en: 'Leg extension', sets: 3, reps: '10–15', rest: 90,
      mm: [{ quads: 1 }, {}],
      tip: { hu: 'A comb elejét izolálja. A végén 1 másodpercre szorítsd meg, és lassan engedd vissza.',
             en: 'Isolates the quads. Squeeze for a second at the top and lower slowly.' } },
    { day: 'legs', ex: 'Standing_Calf_Raises', hu: 'Álló vádliemelés', en: 'Standing calf raise', sets: 4, reps: '8–12', rest: 60,
      mm: [{}, { calves: 1 }],
      tip: { hu: 'Nyújtott térddel a felszíni ikerizom dolgozik. A sarkat engedd mélyre, felül tarts 1 másodpercet.',
             en: 'With straight knees the gastrocnemius does the work. Drop the heels deep, hold a second at the top.' } },
    { day: 'legs', ex: 'Cable_Crunch', hu: 'Kábeles has (térdelő hasprés)', en: 'Cable crunch', sets: 3, reps: '12–15', rest: 60,
      mm: [{ abs: 1, obliques: 2 }, {}],
      tip: { hu: 'Térdelve, a kötél a fej mellett. A hátad gömbölyítve közelítsd a könyököd a combodhoz; a csípőd szöge végig maradjon ugyanaz.',
             en: 'Kneeling, rope beside the head. Round the back to bring elbows toward thighs; hip angle stays fixed.' } }
  ]
};
