/* Release metadata and visible history shared by the app and service worker. */
(function (scope) {
  const version = '2.14.0';
  const build = '20261008.16';
  const history = [
    {version:'2.14.0',build:'20261008.16',date:'2026-10-08',
      en:['Starter splits now have seven exercises per session and approximately 60–70 minutes including preparation and rest. The five-day split follows the original plan.','Untouched older starter sessions expand automatically; customized sessions and workout history are preserved.','The two video combinations are in Workout → Exercises → Exercise complexes, keeping their original rounds, grips and tempo.'],
      hu:['A kezdő felosztások minden napja hét gyakorlatot és az előkészülettel, pihenőkkel együtt körülbelül 60–70 percet tartalmaz. Az ötnapos felosztás az eredeti tervet követi.','A korábbi, érintetlen kezdő edzések automatikusan bővülnek; az egyéni módosítások és az edzésnapló megmaradnak.','A két videós kombináció az Edzés → Gyakorlatok → Gyakorlatkomplexek részen található, az eredeti körökkel, fogásokkal és tempóval.']},
    {version:'2.13.2',build:'20261008.15',date:'2026-10-08',en:['Settings has a compact update button beside Upload in the header.'],hu:['A Beállítások fejlécében a Feltöltés mellett kompakt frissítésgomb található.']},
    {version:'2.13.1',build:'20261008.14',date:'2026-10-08',
      en:['Cardio actions stay inside their card; phones show the Add button below the description.','Shared button, action-grid and heading-row sizing lets long labels wrap without squeezing adjacent content.'],
      hu:['A kardió műveletei a kártyán belül maradnak; telefonon a Hozzáadás gomb a leírás alá kerül.','A közös gombok, műveleti sorok és címsorok hosszabb feliratai is törhetők, a szomszédos tartalom összenyomása nélkül.']},
    {version:'2.13.0',build:'20261008.13',date:'2026-10-08',
      en:['Consistent tab transitions and button feedback, plus switches for on/off preferences.','New Crimson red and Royal blue palettes; all routine symbols follow the selected accent.','Profile now has Overview, Your lift ranks and Friends pages. New Goals and routine icons.','Five optional editable starter splits in Plans, with previews and grouped sessions.','Remove any routine, including built-in sessions, without deleting workout history. Empty plans stay empty after reload.'],
      hu:['Egységes fülváltások és gombvisszajelzés, kapcsolók a be/ki beállításokhoz.','Új karmazsinpiros és királykék paletta; minden edzésszimbólum követi a választott színt.','A Profilban Áttekintés, Emelési rangjaid és Barátok oldal. Új Célok- és edzésikonok.','Öt választható, szerkeszthető kezdő felosztás a Tervekben, előnézettel és csoportosított napokkal.','Bármely edzésterv eltávolítható, a beépített napok is. A napló megmarad, az üres lista újratöltéskor is üres marad.']},
    {version:'2.12.0',build:'20261008.12',date:'2026-10-08',
      en:['Profile has separate Overview and Friends pages.','Simpler friend search, visible connections and optional weekly competition.','Existing saved usernames publish automatically when their social profile is missing. Username search accepts @; clearer guidance for contacts and missing profiles.'],
      hu:['A Profil külön Áttekintés és Barátok oldalt kapott.','Egyszerűbb barátkeresés, látható kapcsolatok és lenyitható heti verseny.','A meglévő mentett felhasználónév automatikusan közzétehető, ha hiányzik a közösségi profil. A keresés elfogadja a @ jelet; egyértelműbb segítség a hiányzó profilhoz és elérhetőséghez.']},
    {version:'2.11.0',build:'20261008.11',date:'2026-10-08',
      en:['Illustrative serving images for all 19 recipe ideas, with larger references in recipe details and offline support.','Accent colors now update card outlines and the bottom navigation tint.','Custom color stays expanded when changing accent, background or resetting the hue.'],
      hu:['Illusztratív tálalási képek mind a 19 receptötlethez, nagyobb képpel a részleteknél és offline támogatással.','A kiemelő szín a kártyák körvonalát és az alsó navigáció árnyalatát is frissíti.','Az egyéni szín nyitva marad a kiemelő szín, háttér vagy színalaphelyzet módosításakor.']},
    {version:'2.10.1',build:'20261008.10',date:'2026-10-08',en:['Food now uses the same lined calorie clock as Profile, including the optional exercise-adjusted daily budget.'],hu:['Az Étkezés ugyanazt a vonalas kalóriaórát használja, mint a Profil, az opcionálisan edzéssel növelt napi kerettel.']},
    {version:'2.10.0',build:'20261008.9',date:'2026-10-08',
      en:['Estimated active calories for lifting from confirmed duration, body weight and intensity.','Log walking, incline walking, running, stairs, cycling and elliptical cardio, separately or inside a workout.','Food and Profile separate lifting/cardio calories from your base target; adding them to the daily budget is optional.','Entered daily active calories replace workout estimates in the budget to avoid counting them twice.'],
      hu:['Súlyzós aktív kalóriák becslése ellenőrzött időtartam, testsúly és intenzitás alapján.','Séta, emelkedős séta, futás, lépcsőzés, kerékpározás és elliptikus kardió rögzítése önállóan vagy edzésen belül.','Az Étkezés és Profil külön mutatja a súlyzós és kardió kalóriát, az alapcélt megtartva. A napi keretbe való beszámítás választható.','A megadott napi összes aktív kalória az edzésbecslést helyettesíti, így nem számoljuk kétszer.']},
    {version:'2.9.1',build:'20261008.8',date:'2026-10-08',en:['Profile macro totals show at most one decimal and stay inside their columns.'],hu:['A profil makróértékei legfeljebb egy tizedessel jelennek meg, és az oszlopaikon belül maradnak.']},
    {version:'2.9.0',build:'20261008.7',date:'2026-10-08',
      en:['Setora is the new working name. Existing accounts and diaries stay in place.','Settings is a full tab with visible navigation, curated palettes and background previews.','Lined progress dials, clearer food actions, sticky workout navigation and corrected lift-rank arrows.','Friend search supports username, verified email and verified phone. Contact discovery requires the new database migration and optional SMS configuration.'],
      hu:['Az új munkanév Setora. A fiókok és naplók megmaradnak.','A Beállítások teljes fület kapott látható navigációval, színpalettákkal és háttérelőnézetekkel.','Vonalas haladásmérő, egyértelműbb étkezési műveletek, rögzített edzésnavigáció és javított rangnyilak.','Barátkeresés felhasználónévvel, igazolt emaillel és telefonnal. Az elérhetőség alapú kereséshez új adatbázis-bővítés és opcionálisan SMS-beállítás szükséges.']},
    {version:'2.8.1',build:'20261008.6',date:'2026-10-08',
      hu:['Visszaállítottuk a korábbi, részletes izomrajzokat.','A gyakorlatok megnyitásakor ismét a mozdulatképek jelennek meg először.','A személyre szabott regisztráció és az új navigáció megmaradt.'],
      en:['Restored the previous detailed muscle drawings.','Exercise details show movement images first again.','Personalized registration and the updated navigation are retained.']},
    {version:'2.8.0',build:'20261008.5',date:'2026-10-08',
      hu:['Személyre szabott regisztráció: cél, nem, kor, magasság, testsúly és aktivitás alapján kezdő kalóriacél.','Saját elöl–hátul izomtérkép piros főizom-kiemeléssel. Külön Izmok és Mozdulat nézet.','A Célok középre, a Beállítások a Profil mellé került. Felül csak a feltöltés maradt.','Frissítési útmutató a főképernyős névhez és ikonhoz; a régi iPhone-könyvjelzők átnevezését az iOS kezeli.'],
      en:['Personalized signup calculates starting calories from your goal, sex, age, height, weight and activity.','Original front/back anatomy highlights primary muscles in red. Separate Muscles and Movement views.','Goals is centered and Settings is beside Profile. The header keeps the upload button.','Home-screen name/icon update guidance, including iOS bookmark limitations.']},
    {version:'2.7.0',build:'20261008.4',date:'2026-10-08',
      hu:['Új, egységes grafit–barack–levendula arculat, hozzá illő világos témával.','Megújult az Edzés, Étkezés, Célok, Profil, Beállítások és a tervfeltöltés megjelenése.','Egységesebb kártyák, gombok, mezők, naptárak és alsó navigáció. A saját szín- és akadálymentesítési beállítások megmaradnak.'],
      en:['A cohesive graphite, apricot and lavender design, with a matching light theme.','Refreshed Workout, Food, Goals, Profile, Settings and plan uploads.','Consistent cards, controls, calendars and bottom navigation. Custom colors and accessibility preferences are retained.']},
    {version:'2.6.1',build:'20261008.3',date:'2026-10-08',
      en:['A new name: Otisport, with a fresh mint O app icon.','New home-screen, browser and sign-in branding. Your existing workouts, meals and account stay in place.'],
      hu:['Új név: Otisport, új mentaszínű O alkalmazásikonnal.','Új kezdőképernyős, böngészős és bejelentkezési arculat. Az edzések, étkezések és a fiókod megmaradnak.']},
    {version:'2.6.0',build:'20261008.2',date:'2026-10-08',
      en:['New bottom navigation: Workout, Food, Settings, Goals and Profile. Exercises now live inside Workout.','Customize your profile with a photo, bio, colors and individually selected earned badges.','Daily calories appear in a clock-style dial; lift ranks and milestones are together in Profile.','Usernames, friend requests and weekly competition connect to the new social database migration.'],
      hu:['Új alsó menü: Edzés, Étkezés, Beállítások, Célok és Profil. A gyakorlatok az Edzésen belül találhatók.','Profilfotó, bemutatkozás, színek és egyenként kiválasztható, megszerzett jelvények.','Óraszerű kalóriamérő, emelési rangok és mérföldkövek a Profilban.','Felhasználónevek, baráti kérések és heti verseny az új közösségi adatbázis-bővítéssel.']},
    {version:'2.5.1',build:'20261008.1',date:'2026-10-08',
      hu:['A nagyított gyakorlatképek és más párbeszédablakok mögött a háttér nem görgethető és nem érinthető.','Bezáráskor az oldal az előző helyére tér vissza, egymásra nyitott ablakok után is.'],
      en:['Exercise image zoom and other dialogs now block background scrolling and interaction.','Closing the last dialog restores the page position, including nested views and plan uploads.']},
    {version:'2.5.0',build:'20261007.13',date:'2026-10-07',
      hu:['Kompakt tervfeltöltés a Beállítások mellett és összecsukható heti étrend.','Az Edzés oldal külön Edzés, Tervek, Napló és Rangok nézetet kapott.','Edzés közben közvetlenül választhatsz gyakorlatot; az összterhelésből látszanak a naplózott emelések.','Hat egyéni emelési rang négy rudas alapgyakorlathoz, tényleges munkasorozatok alapján.'],
      en:['Compact plan upload beside Settings and collapsible weekly meals.','The Workout page now has Train, Plans, History and Ranks views.','Jump directly to exercises during a workout and expand volume to inspect your lifts.','Six personal lift ranks across four barbell exercises, using actual working sets.']},
    {version:'2.4.3',build:'20261007.12',date:'2026-10-07',
      hu:['A frissítés minden alkalmazásfájlt ellenőriz, mielőtt az új verziót aktiválja.','A PDF-beolvasó és a többi alkalmazásfájl azonos kiadásból töltődik be.','A hiányzó rajzok helyén a meglévő kezdő- és véghelyzet-fotók jelennek meg.'],
      en:['Updates verify every app file before activating the new version.','The PDF reader and the rest of the app load from the same verified release.','Existing start/end photos fill the gaps where drawings are not ready.']},
    {version:'2.4.2',build:'20261007.11',date:'2026-10-07',
      hu:['A PDF-táblázatok kcal oszlopából az ételek és étkezések kalóriái is beolvashatók.','A Meal total és Meal macros sorokból az étkezési összesítések készülnek.','Az étrendi szabályok megjegyzésként maradnak meg, nem új étkezésként.'],
      en:['Calories are read from labelled kcal columns in PDF food tables.','Meal total and Meal macros lines populate meal nutrition.','Diet rules are retained as notes rather than extra meals.']},
    {version:'2.4.1',build:'20261007.10',date:'2026-10-07',
      hu:['Az importálási előnézet stabil magasságú és külön görgethető; a háttér helyben marad.','Egyedi Push, Pull, Láb, Felsőtest és Alsótest ikonok.'],
      en:['The import preview keeps its height and scrolls independently while the background stays still.','Custom Push, Pull, Legs, Upper and Lower workout icons.']},
    {version:'2.4.0',build:'20261007.9',date:'2026-10-07',
      hu:['Az Excel-oszlopokból edzésnapok és heti étkezések készülnek.','Fájlválasztás után rögtön átnézheted és hozzáadhatod a terveket.','A teljes heti étrend külön nézetet kapott az Étkezésben.','Letisztult mentaszín, új kártyák és lebegő navigáció.'],
      en:['Excel columns become workout days and scheduled weekly meals.','Choose a file, review the preview and add your plans.','A dedicated Meal plan view shows the whole week in Food.','A calmer mint palette, refreshed cards and floating navigation.']},
    {version:'2.3.1',build:'20261007.8',date:'2026-10-07',
      hu:['FileReader tartalékút a régebbi mobilböngészők fájlolvasásához.','Ugyanaz a fájl és kép újra kiválasztható.'],
      en:['FileReader fallback for older mobile browsers.','The same file or image can be selected again.']},
    {version:'2.3.1',build:'20261007.7',date:'2026-10-07',
      hu:['Safari-kompatibilis PDF-szövegkiolvasás és részletesebb hibajelzés.'],
      en:['Safari-compatible PDF text extraction and clearer import errors.']},
    {version:'2.3.0',build:'20261007.6',date:'2026-10-07',
      hu:['Helyi PDF-, Word- és Excel-tervbeolvasás külső adatküldés nélkül.'],
      en:['Local PDF, Word and Excel plan reading without an external upload.']}
  ];
  scope.GYM_RELEASE = Object.freeze({ version, build, history, cacheId: 'v' + version + '-' + build });
})(globalThis);
