/* Release metadata and visible history shared by the app and service worker. */
(function (scope) {
  const version = '2.8.1';
  const build = '20261008.6';
  const history = [
    {version,build,date:'2026-10-08',
      hu:['Visszaállítottuk a korábbi, részletes izomrajzokat.','A gyakorlatok megnyitásakor ismét a mozdulatképek jelennek meg először.','A személyre szabott regisztráció és az új navigáció megmaradt.'],
      en:['Restored the previous detailed muscle drawings.','Exercise details show movement images first again.','Personalized registration and the updated navigation are retained.']},
    {version:'2.8.0',build:'20261008.5',date:'2026-10-08',
      hu:['Személyre szabott regisztráció: cél, nem, kor, magasság, testsúly és aktivitás alapján kezdő kalóriacél.','Saját elöl–hátul izomtérkép piros főizom-kiemeléssel. Külön Izmok és Mozdulat nézet.','A Célok középre, a Beállítások a Profil mellé került. Felül csak a feltöltés maradt.','Frissítési útmutató a főképernyős névhez és ikonhoz; a régi iPhone-könyvjelzők átnevezését az iOS kezeli.'],
      en:['Personalized signup calculates starting calories from your goal, sex, age, height, weight and activity.','Original front/back anatomy highlights primary muscles in red. Separate Muscles and Movement views.','Goals is centered and Settings is beside Profile. The header keeps the upload button.','Home-screen name/icon update guidance, including iOS bookmark limitations.']},
    {version:'2.7.0',build:'20261008.4',date:'2026-10-08',
      hu:['Új, egységes grafit–barack–levendula arculat, hozzá illő világos témával.','Megújult az Edzés, Étkezés, Célok, Profil, Beállítások és a tervfeltöltés megjelenése.','Egységesebb kártyák, gombok, mezők, naptárak és alsó navigáció. A saját szín- és akadálymentesítési beállítások megmaradnak.'],
      en:['A cohesive graphite, apricot and lavender design, with a matching light theme.','Refreshed Workout, Food, Goals, Profile, Settings and plan uploads.','Consistent cards, controls, calendars and bottom navigation. Custom colors and accessibility preferences are retained.']},
    {version:'2.6.1',build:'20261008.3',date:'2026-10-08',
      en:['A new name: Otisport, with a fresh mint O app icon.','New home-screen, browser and sign-in branding. Your existing workouts, meals and account stay in place.'],
      hu:['Új név: Otisport, új mentaszínű O alkalmazásikonnal.','Új kezdőképernyős, böngészős és bejelentkezési arculat. Az edzések, étkezések és a fiókod megmaradnak.']},
    {version:'2.6.0',build:'20261008.2',date:'2026-10-08',
      en:['New bottom navigation: Workout, Food, Settings, Goals and Profile. Exercises now live inside Workout.','Customize your profile with a photo, bio, colors and individually selected earned badges.','Daily calories appear in a clock-style dial; lift ranks and milestones are together in Profile.','Usernames, friend requests and weekly competition connect to the new social database migration.'],
      hu:['Új alsó menü: Edzés, Étkezés, Beállítások, Célok és Profil. A gyakorlatok az Edzésen belül találhatók.','Profilfotó, bemutatkozás, színek és egyenként kiválasztható, megszerzett jelvények.','Óraszerű kalóriamérő, emelési rangok és mérföldkövek a Profilban.','Felhasználónevek, baráti kérések és heti verseny az új közösségi adatbázis-bővítéssel.']},
    {version:'2.5.1',build:'20261008.1',date:'2026-10-08',
      hu:['A nagyított gyakorlatképek és más párbeszédablakok mögött a háttér nem görgethető és nem érinthető.','Bezáráskor az oldal az előző helyére tér vissza, egymásra nyitott ablakok után is.'],
      en:['Exercise image zoom and other dialogs now block background scrolling and interaction.','Closing the last dialog restores the page position, including nested views and plan uploads.']},
    {version:'2.5.0',build:'20261007.13',date:'2026-10-07',
      hu:['Kompakt tervfeltöltés a Beállítások mellett és összecsukható heti étrend.','Az Edzés oldal külön Edzés, Tervek, Napló és Rangok nézetet kapott.','Edzés közben közvetlenül választhatsz gyakorlatot; az összterhelésből látszanak a naplózott emelések.','Hat egyéni emelési rang négy rudas alapgyakorlathoz, tényleges munkasorozatok alapján.'],
      en:['Compact plan upload beside Settings and collapsible weekly meals.','The Workout page now has Train, Plans, History and Ranks views.','Jump directly to exercises during a workout and expand volume to inspect your lifts.','Six personal lift ranks across four barbell exercises, using actual working sets.']},
    {version:'2.4.3',build:'20261007.12',date:'2026-10-07',
      hu:['A frissítés minden alkalmazásfájlt ellenőriz, mielőtt az új verziót aktiválja.','A PDF-beolvasó és a többi alkalmazásfájl azonos kiadásból töltődik be.','A hiányzó rajzok helyén a meglévő kezdő- és véghelyzet-fotók jelennek meg.'],
      en:['Updates verify every app file before activating the new version.','The PDF reader and the rest of the app load from the same verified release.','Existing start/end photos fill the gaps where drawings are not ready.']},
    {version:'2.4.2',build:'20261007.11',date:'2026-10-07',
      hu:['A PDF-táblázatok kcal oszlopából az ételek és étkezések kalóriái is beolvashatók.','A Meal total és Meal macros sorokból az étkezési összesítések készülnek.','Az étrendi szabályok megjegyzésként maradnak meg, nem új étkezésként.'],
      en:['Calories are read from labelled kcal columns in PDF food tables.','Meal total and Meal macros lines populate meal nutrition.','Diet rules are retained as notes rather than extra meals.']},
    {version:'2.4.1',build:'20261007.10',date:'2026-10-07',
      hu:['Az importálási előnézet stabil magasságú és külön görgethető; a háttér helyben marad.','Egyedi Push, Pull, Láb, Felsőtest és Alsótest ikonok.'],
      en:['The import preview keeps its height and scrolls independently while the background stays still.','Custom Push, Pull, Legs, Upper and Lower workout icons.']},
    {version:'2.4.0',build:'20261007.9',date:'2026-10-07',
      hu:['Az Excel-oszlopokból edzésnapok és heti étkezések készülnek.','Fájlválasztás után rögtön átnézheted és hozzáadhatod a terveket.','A teljes heti étrend külön nézetet kapott az Étkezésben.','Letisztult mentaszín, új kártyák és lebegő navigáció.'],
      en:['Excel columns become workout days and scheduled weekly meals.','Choose a file, review the preview and add your plans.','A dedicated Meal plan view shows the whole week in Food.','A calmer mint palette, refreshed cards and floating navigation.']},
    {version:'2.3.1',build:'20261007.8',date:'2026-10-07',
      hu:['FileReader tartalékút a régebbi mobilböngészők fájlolvasásához.','Ugyanaz a fájl és kép újra kiválasztható.'],
      en:['FileReader fallback for older mobile browsers.','The same file or image can be selected again.']},
    {version:'2.3.1',build:'20261007.7',date:'2026-10-07',
      hu:['Safari-kompatibilis PDF-szövegkiolvasás és részletesebb hibajelzés.'],
      en:['Safari-compatible PDF text extraction and clearer import errors.']},
    {version:'2.3.0',build:'20261007.6',date:'2026-10-07',
      hu:['Helyi PDF-, Word- és Excel-tervbeolvasás külső adatküldés nélkül.'],
      en:['Local PDF, Word and Excel plan reading without an external upload.']}
  ];
  scope.GYM_RELEASE = Object.freeze({ version, build, history, cacheId: 'v' + version + '-' + build });
})(globalThis);
