/* Exact JS/PostgreSQL parity and negative cases on a disposable database. */
import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const {PGlite}=await import(process.argv[2]||'/tmp/reppsy-pg/node_modules/@electric-sql/pglite/dist/index.js');
const context=vm.createContext({window:{},Date,Set,Map});vm.runInContext(fs.readFileSync('js/competition.js','utf8'),context);const C=context.window.Competition;vm.runInContext(fs.readFileSync('js/strength-ranks.js','utf8'),context);vm.runInContext(fs.readFileSync('js/profile.js','utf8'),context);const P=context.window.Profile,R=context.StrengthRanks;
const db=new PGlite(),id='00000000-0000-4000-8000-000000000001';
await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key,raw_user_meta_data jsonb);create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;create table public.userdata(user_id uuid primary key,data jsonb);`);
for(const f of ['20261008_social.sql','20261010_profile_sharing.sql','20261010_consistency_covers.sql'])await db.exec(fs.readFileSync(new URL('../migrations/'+f,import.meta.url),'utf8'));
await db.query('insert into auth.users values($1,$2)',[id,{reppsy_username:'test_owner'}]);await db.exec('begin');
const now=Number((await db.query('select floor(extract(epoch from now())*1000)::text as ms')).rows[0].ms),stamp=new Date(now);stamp.setUTCHours(0,0,0,0);stamp.setUTCDate(stamp.getUTCDate()-(stamp.getUTCDay()+6)%7);const first=+stamp,at=Math.max(first,now-1000),today=new Date(now).toISOString().slice(0,10);
const tick={id:'tick',start:at,end:at,tick:true,entries:[],pl:[{ex:'Barbell_Bench_Press_-_Medium_Grip',n:7}]};
const lift={id:'lift',start:at,end:at,entries:[{ex:'Barbell_Bench_Press_-_Medium_Grip',sets:[{kg:60,reps:10},{kg:0,reps:10},{kg:80,reps:0},{kg:200,reps:5,w:true}]}]};
const meal=(id,pm='')=>({id,pm,kcal:400,name:'PRIVATE MEAL',p:25,c:50,f:10});
const data={workouts:[tick,{...tick,id:'tick2'},lift,{...tick,start:first-2000,end:first-2000},{...tick,start:now+1000,end:now+1000},{...tick,id:'empty',pl:[]}],food:{[today]:[meal('a','pm1'),meal('a-copy','pm1'),meal('b','pm2'),meal('c','pm3'),meal('d','pm4'),{id:'water',kcal:0},{id:'bad',kcal:9999999}]}};
const parity=async(data)=>{await db.query('insert into public.userdata values($1,$2) on conflict(user_id) do update set data=excluded.data',[id,data]);const actual=(await db.query('select public.social_stats($1) as s',[id])).rows[0].s,expected=C.week(data,now);for(const k of ['score','days','sets','attendance_points','set_points','workout_points','meal_points','meal_days'])assert.equal(actual[k],expected[k],k);const badges=P.summary(data.workouts||[],now,data.food||{}).badges.filter(b=>b.earned).map(b=>b.id).sort();assert.equal(JSON.stringify(actual.badges.slice().sort()),JSON.stringify(badges),'badge parity');return actual;};
let s=await parity(data);assert.equal(s.score,170);assert.equal(s.workouts,1);assert.equal(s.volume,600);assert.equal(s.highest,5);
s=await parity({workouts:[tick],food:{[today]:[meal('one')]}});assert.equal(s.score,120);assert.equal(s.volume,0);assert.equal(s.highest,-1);assert.equal(s.badges.length,0);
s=await parity({workouts:[],food:{[today]:[meal('one')]}});assert.equal(s.score,20);
s=await parity({workouts:[lift,{...lift,id:'more',entries:[{ex:'Bodyweight_Squat',sets:Array.from({length:40},()=>({kg:0,reps:8}))}]}],food:{[today]:Array.from({length:30},(_,i)=>meal('meal'+i))}});assert.equal(s.score,260);
s=await parity({workouts:[{start:at,end:at,entries:[],cardio:[{weight:80,minutes:25}]}],food:{}});assert.equal(s.score,100);assert.equal(s.volume,0);
s=await parity({workouts:[{start:at,end:0,entries:lift.entries},{...tick,start:now+1000,end:now+1000},{...lift,entries:[{sets:[{kg:10,reps:0},{kg:10,reps:8,w:true}]}]}],food:{'2999-01-01':[meal('future')]}});assert.equal(s.score,0);
const history=Array.from({length:7},(_,i)=>({...tick,id:'history'+i,start:at-i*86400000,end:at-i*86400000}));const diary=Object.fromEntries(history.map((w,i)=>[new Date(w.start).toISOString().slice(0,10),[meal('history'+i)]]));s=await parity({workouts:history,food:diary});assert.ok(s.badges.includes('checkins'));assert.ok(s.badges.includes('food'));s=await parity({workouts:Array.from({length:5},(_,i)=>({...lift,id:'lift'+i,start:at-i*86400000,end:at-i*86400000})),food:{}});assert.ok(s.badges.includes('five'));assert.ok(!s.badges.includes('balance'));
for(const track of R.tracks){for(let i=0;i<track.weights.length;i++){const kg=track.weights[i];assert.equal(R.summary([{entries:[{ex:track.ex,sets:[{kg,reps:1}]}]}]).find(r=>r.id===track.id).tier,i);assert.equal(R.summary([{entries:[{ex:track.ex,sets:[{kg:kg-0.01,reps:1}]}]}]).find(r=>r.id===track.id).tier,i-1);s=await parity({workouts:[{...lift,entries:[{ex:track.ex,sets:[{kg,reps:1}]}]}],food:{}});assert.equal(s.highest,i);}}
assert.equal(R.tiers[7].en,'Titan');
await parity(data);await db.query("select set_config('request.jwt.claim.sub',$1,true)",[id]);await db.exec('set local role authenticated');const dashboard=(await db.query('select public.social_dashboard_v2() as d')).rows[0].d;assert.equal(dashboard.leaderboard[0].score,170);assert.equal(dashboard.leaderboard[0].meal_points,60);assert.equal(JSON.stringify(dashboard).includes('PRIVATE MEAL'),false);await assert.rejects(db.query('select public.social_consistency($1)',[id]),/permission denied/);
await db.exec('rollback');await db.close();
assert.equal(C.rank(0).en,'Starting');assert.equal(C.rank(300).en,'Finding rhythm');assert.equal(C.rank(1200).en,'Momentum');
console.log('PASS: JS/SQL parity; check-ins, cardio, meal ticks, undo, week bounds, daily caps, zero-calorie exclusion, real lift ranks and aggregate-only privacy.');
